### ISSUE TITLE
Data batching limits

### ISSUE THREAD

**Issue by AndreaMKing5** [dimagi/commcare-export#160] opened 2020-10-20 18:59 UTC
If there are more than 1k cases updated, DET gives the cases the same time stamp.  Could this limit either be increased (or would that cause any performance related issues?)

Note - this issue may have been addressed already, so possibly a first step is confirming the current limit.

**Comment by proteusvacuum** [comment] 2020-10-20 19:33
I think this: https://github.com/dimagi/commcare-export/pull/159 should solve this issue once it is merged

**Comment by snopoke** [comment] 2020-10-26 06:35
> DET gives the cases the same time stamp

Can you explain more about what you mean. The DET doesn't give cases any timestamps at all.

**Comment by proteusvacuum** [comment] 2020-10-27 14:20
@snopoke it is referencing this: https://github.com/dimagi/commcare-export/issues/107#issuecomment-435052926 
I believe @AndreaMKing5 meant that the DET can't export more than `batch_limit` number of cases with the same modified date, so gets stuck. Closing this as a dupe of that issue.

**Closed by proteusvacuum** 2020-10-27 14:20 UTC
